### ISSUE TITLE
Model size

### ISSUE THREAD

**Issue by AGrosserHH** [aosokin/os2d#10]
Hi all, 

I am trying to train the model and I have got Nvidia GPU Titan 1080 with 11GM RAM I am also doing the hard mining with using the option train.cache_images FALSE. However, at the end of the hard mining procss I get an error message that the graphic card is running out of memory. Is there any opportunity to decrease the memory size?

Thanks in advance,
Andi

**Comment by aosokin** [comment]
Hi, thanks for your interest!
I think we never trained models with hard patch mining on Titan GPUs - always used Volta.
Generally speaking, you need to cut down memory usage: reduce batch size, image resolution, number fo pyramid levels, number of class image, etc. Do you have an understanding where most memory is used?
Best,
Anton

**Comment by AGrosserHH** [comment]
Thanks! It helped to decrease the scale size.
