### ISSUE TITLE
sampling function

### ISSUE THREAD

**Issue by roitmaster** [aosokin/os2d#16]
Hi, can you give a small explanation of how did you implement your fast sampling?

**Comment by aosokin** [comment]
Hi, was your question about the method resample_of_correlation_map_fast? 
https://github.com/aosokin/os2d/blob/96c488b3979c505b92245ccdab941fb01fdf99de/os2d/modeling/head.py#L439

Here, the key idea was to call `F.grid_sample` only once and only at the points that are needed for the computation. To do that, we merged several correlation maps into one "long" map by stitching (with the view op) several dimensions of the correlation tensor together. Then, we recompute the coordinates of the sampling points to resample from the "long" map.

**Comment by roitmaster** [comment]
thanks
