### ISSUE TITLE
multiple gpus for training

### ISSUE THREAD

**Issue by WeitaoVan** [aosokin/os2d#17]
Hi aosokin,

Thanks for sharing the great work!

May I ask how to assign the number of GPUs used for training?
For example, I want to train 'V2-train' using 4 GPUs. 

Thank you.

**Comment by aosokin** [comment]
Hi, unfortunately, we did not implement multi-GPU support.
However, this should be easy to do with the help of DistributedDataParallel

**Comment by aosokin** [comment]
In our experiments, 200k iterations of the V2 model without/with hard patch mining took 4.5/6.8 days on V100.
However, this 200k might be a significant overshoot. In particular, around 60-70k steps from the beginning the models start to oscillate and it might make sense to decrease LR there. With the current schedule, we waited for 100k to do the first decrease. The second and third stages (after decreasing LR) can also be much shorter.

For both versions of the INSTRE dataset, the story was the same - 60-70k steps before LR decrease were enough.
Some models can be clearly stopped earlier - you might want to use ReduceLROnPlateau if you want to detect those.

Hope this was helpful!
Best,
Anton

**Comment by WeitaoVan** [comment]
Your detailed explanatios are much appreciated!

Best,
Weitao

**Comment by aosokin** [comment]
Hi, no I haven't tried it and will probably not have time to add it.
Best,
Anton
