### ISSUE TITLE
making the code faster

### ISSUE THREAD

**Issue by roitmaster** [aosokin/os2d#18]
Hi once again awsome work you did

in your head.py lines 371-376 :
default_boxes_xyxy_wrt_fm = self.box_grid_generator_feature_map_level.create_strided_boxes_columnfirst(fm_size=image_fm_size)

```
default_boxes_xyxy_wrt_fm = default_boxes_xyxy_wrt_fm.view(1, 1, image_fm_size.h, image_fm_size.w, 4)
# 1 (to broadcast to batch_size) x 1 (to broadcast to class batch_size) x  box_grid_height x box_grid_width x 4
default_boxes_xyxy_wrt_fm = default_boxes_xyxy_wrt_fm.to(resampling_grids_local_coord.device)
resampling_grids_fm_coord = convert_box_coordinates_local_to_global(resampling_grids_local_coord, default_boxes_xyxy_wrt_fm)
```
and lines 405-410:
```
default_boxes_xyxy_wrt_image = self.box_grid_generator_image_level.create_strided_boxes_columnfirst(fm_size=image_fm_size)
default_boxes_xyxy_wrt_image = default_boxes_xyxy_wrt_image.view(1, 1, image_fm_size.h, image_fm_size.w, 4)
# 1 (to broadcast to batch_size) x 1 (to broadcast to class batch_size) x  box_grid_height x box_grid_width x 4
default_boxes_xyxy_wrt_image = default_boxes_xyxy_wrt_image.to(resampling_grids_local_coord.device)
resampling_grids_image_coord = convert_box_coordinates_local_to_global(resampling_grids_local_coord, default_boxes_xyxy_wrt_image)
```

thus line do the same calculation, and they don't have trainable parameters, why we can't reuse the first calculation for the second one?

**Comment by aosokin** [comment]
Note that line 371
https://github.com/aosokin/os2d/blob/96c488b3979c505b92245ccdab941fb01fdf99de/os2d/modeling/head.py#L371
and line 405
https://github.com/aosokin/os2d/blob/96c488b3979c505b92245ccdab941fb01fdf99de/os2d/modeling/head.py#L405
depend on self.box_grid_generator_feature_map_level and self.box_grid_generator_image_level, respectively.
These two are different objects:
https://github.com/aosokin/os2d/blob/96c488b3979c505b92245ccdab941fb01fdf99de/os2d/modeling/head.py#L218-L220
If I remember correctly, the first one produces boxes in the coordinates w.r.t. the feature map, the second one - w.r.t. the input image.
