### ISSUE TITLE
trainning from scratch

### ISSUE THREAD

**Issue by roitmaster** [aosokin/os2d#19]
hi

I the paper wroten that you trained the transform net from the model that has been pre-trained with weakalign.

I the repo "https://github.com/ignacio-rocco/weakalign.git" the architecture is different than yours. (two stages vs. one stage)
so how did you did it ?

**Comment by aosokin** [comment]
Hi, in our paper, we used only the affine transformations from weakalign. Please see this function https://github.com/aosokin/os2d/blob/96c488b3979c505b92245ccdab941fb01fdf99de/os2d/modeling/model.py#L389
on how we loaded their weights into our model.
Best,
Anton

**Comment by roitmaster** [comment]
why didn't you tried to use thin-plate spline (TPS) transformation that refines the alignment?

**Comment by aosokin** [comment]
We tried after the paper but could not get significant improvements. The TPS model was designed with two stages requiring image resampling between them. This was too slow when put into OS2D. We made it work with some workarounds but could not get stable improvements over the linear model, and it was still very slow.
