### ISSUE TITLE
How can I train the model with custom dataset?

### ISSUE THREAD

**Issue by dungmn** [aosokin/os2d#24]

**Comment by aosokin** [comment]
Hi, to use a custom dataset, you need to implement a function constructing your dataset in the training mode.
Please, see the two following functions for examples:
https://github.com/aosokin/os2d/blob/96c488b3979c505b92245ccdab941fb01fdf99de/os2d/data/dataset.py#L76
https://github.com/aosokin/os2d/blob/96c488b3979c505b92245ccdab941fb01fdf99de/os2d/data/dataset.py#L405
Best,
Anton

**Comment by saswat0** [comment]
@dungmn Were you able to implement the dataloader for any custom dataset?
