### ISSUE TITLE
How to visualize the test results?

### ISSUE THREAD

**Issue by ziyi2018** [aosokin/os2d#25]
Your work is excellent. Thank you for your work. How to visualize the test results?

**Comment by aosokin** [comment]
Hi, thanks!

You can use some tolls implemented [here](https://github.com/aosokin/os2d/blob/master/os2d/utils/visualization.py). Please checkout our [demo ](https://github.com/aosokin/os2d/blob/master/demo.ipynb) for usage example.

If you want some visualizations of the model internals please checkout these config parameters:
https://github.com/aosokin/os2d/blob/96c488b3979c505b92245ccdab941fb01fdf99de/os2d/config.py#L250-L271

Best,
Anton
