### ISSUE TITLE
Number of iterations

### ISSUE THREAD

**Issue by FSDS0696** [aosokin/os2d#26]
I am trying to run the code for one-shot object detection, but I am not able to complete 5000 iterations. I want to try for less number of iterations, how can I edit the number of iterations?
Thank you in advance.

**Comment by aosokin** [comment]
Hi, I'm not sure I understand what 5000 iterations you mentioned.
The default number of iterations for training is set to 200k if I remember correctly:
https://github.com/aosokin/os2d/blob/96c488b3979c505b92245ccdab941fb01fdf99de/os2d/config.py#L142

But that number is definitely overshooting, so doing less should be fine. For V2 model (initialized not from scratch), doing much less should be fine.

Best,
Anton
