### ISSUE TITLE
How to train the same model for custom data

### ISSUE THREAD

**Issue by FSDS0696** [aosokin/os2d#27]
Hello, thanx for the help.
Now, I am trying to train the model for my own images.
I put my images in the data/demo folder and also change number of iterations in the cfg.
Can you please suggest what more changes that I should do and also the command to train the model.

Thanks in advance.

**Comment by aosokin** [comment]
Hi, unfortunally we did not provide explicit functionality for training on custom datasets.
Please see one of the previous replies for advice how to do this: https://github.com/aosokin/os2d/issues/24#issuecomment-1056713414

Best,
Anton
