### ISSUE TITLE
Reproducing the model results on the paste-f dataset shown in the research paper

### ISSUE THREAD

**Issue by Likhith-Sugganahalli** [aosokin/os2d#28]
Hi, thanks a lot for your work!

I tried reproducing the model results shown in figure 3 of the research paper, shown below.
![image](https://user-images.githubusercontent.com/44597096/175006682-b1d1048c-b35a-4eff-bd82-883e22a0e645.png)

running the demo using the respective images yielded the following result
![result_failed](https://user-images.githubusercontent.com/44597096/175007598-8d135334-d949-4a29-809a-b6cc303964c2.png)

![class_failed](https://user-images.githubusercontent.com/44597096/175007648-2e83f559-f7e6-4aa0-87ec-23411f258968.png)

 class image being 3547.jpg and the test image being 16486.jpg

is this related to the class pyramids not being implemented in the demo?

**Comment by aosokin** [comment]
Hi, yes, to reproduce that result you definitly need  a class pyramid, or at least a scale that will correspond to boxes smaller w.r.t. the shelf image.
Best,
Anton

**Comment by Likhith-Sugganahalli** [comment]
@aosokin Hi anton, could you please share any material i can use to try and understand how to implement a scale pyramid without compromising a lot on the inference speed

**Comment by aosokin** [comment]
A scale pyramid comes at a cost of inference speed because all the different scales have to be processed. If the range of object sizes in your data is not that large, e.g., all the objects are toughly of the same size, than you can try to pre-select fewer scales without covering a large range. Hope this is somewhat helpful :-)

**Comment by Likhith-Sugganahalli** [comment]
@aosokin Hey anton, could you point me towards your implementation, i am trying to generate class images at different scale using skimage transforms, and the results arent any better

**Comment by aosokin** [comment]
Hi, I've run the demo on the images you provided converted to one correct scale: [link](https://gist.github.com/aosokin/38842f09a4524ee3e8696f22a4b72df8)
Here is the result:
![image](https://user-images.githubusercontent.com/2099291/175315146-d8dcf2cd-cd37-4858-bfbc-4741c56f7c2e.png)

Best,
Anton

**Comment by Likhith-Sugganahalli** [comment]
@aosokin thanks a lot for your help
