### ISSUE TITLE
how to use multiple input images in demo.ipynb

### ISSUE THREAD

**Issue by Dawdleryang** [aosokin/os2d#3]
Dear Aosokin,

Thank you for the great job here, especially the detailed descriptions how to set-up the experiments and reproduce the results. 

In your demo.ipynb, a single image used as the input, wondering if any way to use multiple (whole) images within one directory as the input? To scale up the demo.  

Thank you.

**Comment by aosokin** [comment]
Hi, thanks for your interest!
I guess the easiest way to go is to loop blocks 5, 7, and 8-14 over your images.
Best,
Anton

**Comment by Dawdleryang** [comment]
Thank you for the quick reply, that means we cannot use the batch for the input images, like input_images = [read_image(file1), read_image(file2),...], right?

**Comment by aosokin** [comment]
Using batches will require a bit more work: 
- update block 7 to merge images into a batch
- update blocks 11-13 to split network output and run decoding (NMS inside) separately for each image.

The network forward pass (block 9) should work fine for batches of images

**Comment by Dawdleryang** [comment]
Thank you for all the help here. Still cannot manage to make it work, will you consider to come out a batch version later?

**Comment by aosokin** [comment]
For now, I did not plan to do that. Btw, we also did not use batches of input images at the test time of our experiments because they were not bringing significant speedups.

**Comment by Dawdleryang** [comment]
Sure, thank you very much.
