### ISSUE TITLE
how about using the Efficient Neighbourhood Consensus Networks?

### ISSUE THREAD

**Issue by zhangliukun** [aosokin/os2d#30]
Thanks for your great job. Have you tried the paper "Efficient Neighbourhood Consensus Networks via Submanifold Sparse Convolutions"  to replace current correlation map? 
I am wondering if it is necessary to try it, could you give me some suggentions?

**Comment by aosokin** [comment]
Hi, we tried some elements of that direction but stopped when 4D convolutions appeared to be too slow to work on our relatively high-res images. And we had to keep them high-res because we wanted to detect small objects.
However, we definitely did not experiment with this direction sufficiently.

**Comment by zhangliukun** [comment]
Thanks for answering.
By the way, if I want to improve the generalization of the model, it is a good choice to train it using the COCO or the object365 dataset?  
I tried the v2 model in some unseen object, it is not very good if the object is large. So maybe a large dataset is better?
Some new paper of one-shot object detection like "Balanced and Hierarchical Relation Learning for One-shot Object Detection"  trained using the coco perform better in the large object.

**Comment by aosokin** [comment]
Our model was designed with mostly intance-level recognition in mind, which does not go too well with broad categories as in COCO. Another thing to keep in mind is that the current linear transformation model does not suit non-rigid objects (can still work to some extend). I'm actually quite sceptical on the one-shot setting for broad classes like in COCO. It looks like for these kind of things one can easliy collect lots of annotation to get regular detectors to work. One-shot or few-shot formulations are better suited elsewhere in my opinion.

To deal with large objects with our model, I recommend to look carefully at the image resolution. The model works best when the size of object to detect (in pixels) rouhly matches the size of the template images (which is built into the model weights).
