### ISSUE TITLE
Questions about the V2 model approach

### ISSUE THREAD

**Issue by zhangliukun** [aosokin/os2d#31]
Hi, thanks for your great work.
I have a question about the V2 approach in the paper. In section 6.1, the V1 approach P=4 allows to have full supervision and the V2 approach P=6 requires weak supervision for training. 

However, I remember the P=6 full affine transformations can also be trained with full supervision by generating random affine params in Rocco's paper "Convolutional neural network architecture for geometric matching".

I am wandering if there has some different?

**Comment by aosokin** [comment]
Hi, indeed, one can train a model with P=6 with weak supervision from scratch.
However, in our experiments,  such models always converged to producing rectangular bounding boxes as if they had P=4, so we decided to go for a simpler approach.
Note that the models used in the works of Rocco were all initially trained with full supervision (on synthetic data), which probably allowed to get to a good weight configuration.
Best,
Anton
