### ISSUE TITLE
Where to get the trained model on Instre and imageNet?

### ISSUE THREAD

**Issue by zhangliukun** [aosokin/os2d#33]
Thanks for your great work. The released v1-train ,v2-init,v2-train models are trained on the grozi3.2k dataset.
How could we get these models trained on the Instre or the Imagenet-LOC dataset? Training one model costs too much time.

**Comment by aosokin** [comment]
Hi, I've managed to dig out some models trained on INSTRE: [gdrive](https://drive.google.com/file/d/1PL1Ac78zuYTLGkgMxe1gGiEWBEuGJIr9/view)
However, I'm not sure whether those are the correct ones and I dot not have capacity to test them.
If everything is correct they should be compatible with the script [launcher_instre_eval.py](https://github.com/aosokin/os2d/blob/master/experiments/launcher_instre_eval.py) when unpacked in the root of OS2D (note that there are more models programmed to for evaluation whereas I've uploaded only the two best ones).

Unfortunately, I have not been able to find any models trained there.

Best,
Anton

**Comment by aosokin** [comment]
I do not remembre any problems like that. I did very long training runs on INSTRE on 32GB GPU and never had any memory leaks.

**Comment by aosokin** [comment]
Please also note that maybe you do not need that many iterations as the quality on validation may already be stale

**Comment by zhangliukun** [comment]
I trained os2d using the INSTRE-all and evaluate on INSTRE-S2-val，and Iter is 60000(200000). Resnet50
loss 0.0282 
loc_smoothL1 1.63 
cls_RLL 0.0282 
cls_RLL_pos 0.02
cls_RLL_neg 0.0079 
mAP0.5  0.8082 
mAPw0.5 0.8208 
recall 0.94
APjointclasses  0.78
the mAP0.5 0.80 is slight higher than the paper 0.777, then the program did crash again. I will try to figure it out why it is.

**Comment by zhangliukun** [comment]
I evaluate these two resnet101 weights on INSTRE-s2-val using the main.py. the mAP 0.5 are 0.8511 and 0.8751. 
I add a new merge NMS to deal with the large object because the large object always has lots of small bboxes. So I merge these which has a high iou bboxes  and it looks good with I use the default weights trained on Grozi3.2k dataset. 

And I run the demo with the resnet101 weights on some images taken by my phone. The both models may get more  false positive.
