### ISSUE TITLE
Same class images with different class_ids get different results?

### ISSUE THREAD

**Issue by zhangliukun** [aosokin/os2d#34]
I get different results when I use the same images with different class_ids. The input images configs in the demo.py  are as blew:

class_images = [ c1.jpg, c1.jpg ]   # the class images are two same images

if I set the class_ids=[0,1] or class_ids=[0,0] , the result is different. I am confused why these setting will lead to it. In my opinion, it should get the same result because the class_images are the same.

**Comment by aosokin** [comment]
If I remember correctly, when setting set class_ids=[0,0] you are effectively merging two classes into one. The effect should be similar to sitting nms_across_classes to True
