### ISSUE TITLE
Attributes of grozi.csv

### ISSUE THREAD

**Issue by saswat0** [aosokin/os2d#35]
Hey Anton,

What's `gtbboxid` in grozi.csv? How is it obtained and significant?

**Comment by aosokin** [comment]
Hi, as far as I remember it is just a unique ID of a bounding box.

**Comment by saswat0** [comment]
In that case, shouldn't it be continuous?

**Comment by aosokin** [comment]
It originiates from the annotation process, and over time it became less continuous because of cleaning and filtering
