### ISSUE TITLE
What is 3264 in the src?

### ISSUE THREAD

**Issue by saswat0** [aosokin/os2d#38]
Hey @aosokin 

How does the number 3264 (folder named by this number and termed as average image size in code) come across? I wanted to test this on a custom dataset but am puzzled as to how to arrive at this figure.

**Comment by aosokin** [comment]
Hi, this number indicates the size of images (I do not remember which dimension exactly) used when preparing data. More about used image sizes can be found [here](https://github.com/aosokin/os2d/blob/96c488b3979c505b92245ccdab941fb01fdf99de/data/dataset_scales.txt)

**Comment by saswat0** [comment]
Got it. Thanks!
