### ISSUE TITLE
Security alert from dependabot

### ISSUE THREAD

**Issue by aosokin** [aosokin/os2d#42]
Hi @Diogo364 ,
I've received a message form github that one of packages your edit depending on has a [security vulnerability](https://github.com/advisories/GHSA-v3c5-jqr6-7qm8):

"An issue discovered in Python Charmers Future 0.18.2 and earlier allows remote attackers to cause a denial of service via crafted Set-Cookie header from malicious web server. "

Would it be possible to do something in [Docker/requirements.txt](https://github.com/aosokin/os2d/blob/master/Docker/requirements.txt) to get rid of this vulnerability?

**Comment by Diogo364** [comment]
Hey @aosokin,

I was reading a bit more about this issue in the link you sent. It is a "denial of service" attack, the main concern is regarding the availability of the service when openly providing it to the web, the attackers might be constantly taking the service down.

This [Future lib](https://pypi.org/project/future/) apparently is meant for python2/3 compatibility (specially for imports [example here](https://python-future.org/imports.html#future-imports)) and it is in the [Python Standard Library](https://docs.python.org/3/library/__future__.html), that is why when I used `pip freeze` to generate the `requirements.txt` this lib appeared.

Having said that I believe we can remove this line from the [Docker.requirements.txt](https://github.com/aosokin/os2d/blob/master/Docker/requirements.txt) without any problem. This change will allow `pip` to install a further version of this lib as they fix all issues. and might silence the Security alert warning.

I will prepare this change and submit it as PR to you. :smile: 

Thank you very much for the message,
Feel free to contact me any further issues.

**Comment by Diogo364** [comment]
Here is the link to the PR.
#43

**Comment by aosokin** [comment]
Thanks a lot!
