### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by saswat0** [aosokin/os2d#46]
Upon evaluating the trained retrieval model, I'm getting a segmentation fault.

This is the snippet that I use to run the eval:
```
python main_detector_retrieval.py  --retrieval_multiscale  --maskrcnn_config_file detector/config/e2e_faster_rcnn_R_101_FPN_1x_multiscale_noClasses.yaml --maskrcnn_weight_file detector/output/exp0000-R-101-noCl-grozi/model_best.pth --retrieval_network_path retrieval/output/grozi/grozi-train-retrieval-rndCropPerImage10_resnet101_gem_whiten_contrastive_m0.85_adam_lr1.0e-06_wd1.0e-04_nnum5_qsize2000_psize20000_bsize32_imsize240/model_epoch0.pth.tar  --retrieval_image_size 240 is_cuda True eval.dataset_names "[\"grozi-val-new-cl\"]" eval.dataset_scales "[1280.0]" eval.mAP_iou_thresholds "[0.5]"
```

This is the error that I get:
```
DeprecatedFeatureWarning: apex.amp is deprecated and will be removed by the end of February 2023. Use [PyTorch AMP](https://pytorch.org/docs/stable/amp.html)
  warnings.warn(msg, DeprecatedFeatureWarning)
Segmentation fault (core dumped)
```

**Comment by aosokin** [comment]
I don't know whether the deprecation warning is related to the segmentation fault at all. It probably needs debugging to identify why this happened.

**Comment by saswat0** [comment]
The deprecation warning is most probably unrelated to the error because I happened to come across this warning many times in other parts of this repository, which executed fine. Did you ever encounter this problem? Or do you have any idea from where this might have originated?

**Comment by aosokin** [comment]
Sorry, I don't remember seeing anythings like this and have no idea where this might be coming from.

**Comment by saswat0** [comment]
Ok
