### ISSUE TITLE
New form of evaluation

### ISSUE THREAD

**Issue by saswat0** [aosokin/os2d#51]
Reusing this codebase, can we get the prediction and ground truths in two text files in the following format?
`<class_name> <left> <top> <right> <bottom> [<difficult>]`

**Comment by aosokin** [comment]
I think the input file (e.g., classes/grozi.csv from [here](https://drive.google.com/open?id=1Fx9lvmjthe3aOqjvKc6MJpMuLF22I1Hp)) is in a format extremely similar to this one. I don't think we ever implemented export in this format but that should be easy to do by saving a file at the end of the [evaluation function](https://github.com/aosokin/os2d/blob/a365ef65d3b541f27de7d62732473c5ace758d2b/os2d/engine/evaluate.py#L172).

**Comment by saswat0** [comment]
Thanks. That's helpful.
Any idea on how to do the same with the baselines as well?

**Comment by aosokin** [comment]
Sorry, I totally do not remember the details about the baselines anymore :-(
