### ISSUE TITLE
some new ideas about YOLO to os2d

### ISSUE THREAD

**Issue by zhangliukun** [aosokin/os2d#57]
Hello, I have some ideas about changing the YOLO ont input branch to  two branch,  and apply the feature matching. Then use the standard YOLO Head to output the detection.  (if not add the STN , the result will be better or worser?)
Could you give me some suggestions about the idea?

**Comment by aosokin** [comment]
I'm sorry but Ive never thought on combining feature matching with YOLO so I probably can't help.
