### ISSUE TITLE
multiple images for same product

### ISSUE THREAD

**Issue by pranav318** [aosokin/os2d#6]

**Comment by pranav318** [comment]
Dear Aosokin,

Thank you for the great job here, especially the detailed descriptions how to set-up the experiments and reproduce the results.
i just want to know can we give multiple images instead of image per product.
Thank You

**Comment by aosokin** [comment]
Hi, thanks for the kind words!
The method itself supports only one class representative, however you can
give it two images as separate classes and then merge before NMS. We
implemented test time augmentation in the form of flips/rotations this way.
Best,
Anton

**Comment by pranav318** [comment]
thanks for clarifying.
