### ISSUE TITLE
Unable to reproduce correct results from demo.ipynb

### ISSUE THREAD

**Issue by shikikansama** [aosokin/os2d#79]
Hello,

I am trying to learn the method described in the demo.ipynb file, but I am encountering difficulties in reproducing the correct results. Despite following the instructions provided, the outcomes differ from what is expected. 

Could someone please offer some guidance or suggestions on how to resolve this issue? Any help would be greatly appreciated.

Thank you!
![QQ截图20240326151348](https://github.com/aosokin/os2d/assets/66072302/30d58886-8d94-49ef-a9e5-e5aabe036b03)

**Comment by aosokin** [comment]
Do the exact examples from the demo notebook work for you?
Some time ago I did [another example](https://github.com/aosokin/os2d/issues/28#issuecomment-1164433110) on applying the demo notebook to some images. Could you try if that runs as is as well?

**Comment by shikikansama** [comment]
Thank you very much for your response. I have been able to run the example successfully.
