### ISSUE TITLE
Did I get enough iterations in my training process?

### ISSUE THREAD

**Issue by lllying** [aosokin/os2d#8]
Dear Anton Osokin：
       Thanks a LOT for your helpful code, I'm trying to apply it on my own datasets but confused about setting some parameters，since I change the data used for training while keeping most parameters setting unchanged, the mAP is not good definitely， However, after 30000 iterations (15 epochs with batch size as 8), I only get 4.7%  and it never increases in the next 50000 iterations. Difficult to judge from the loss values so I want to know whether my training process getting enough iterations and which parameters are vital to the effect of the model when I change the datasets.
Any response would be appreciated! Thanks for your time!

**Comment by aosokin** [comment]
Hi, I can say two things:
1) On a new dataset, I'd start with the model OS2D V2-init - it should work without any training. If it does not produce any meaningful results I think training is not likely to help.
2) When moving to a new dataset train.dataset_scale and eval.dataset_scales are critical since they are somewhat defining the expected object size. For our subsets, even with an image pyramid, we had to set these scales to different values.
Best,
Anton

**Comment by lllying** [comment]
THANK YOU SO MUCH!!!&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aosokin/os2d"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月19日(星期四) 晚上10:47
收件人:&nbsp;"aosokin/os2d"<os2d@noreply.github.com&gt;;
抄送:&nbsp;"0"<1309424778@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [aosokin/os2d] Did I get enough iterations in my training process? (#8)





 
Hi, I can say two things:
  
On a new dataset, I'd start with the model OS2D V2-init - it should work without any training. If it does not produce any meaningful results I think training is not likely to help.
 
When moving to a new dataset train.dataset_scale and eval.dataset_scales are critical since they are somewhat defining the expected object size. For our subsets, even with an image pyramid, we had to set these scales to different values.
 Best,
 Anton
